### ISSUE TITLE
Fill word database with missing words

### ISSUE THREAD

**Issue by DeadSith** [DeadSith/PvP-Scrabble-like-game#10]
Added missing words to database.

**Comment by DeadSith** [comment]
@ua2004 Successfully copied the database you gave me to SQL Server, but it has a problem. None of the tables has primary key. Fortunately, I was able to add keys to all tables without spoiling any data.

**Comment by ua2004** [comment]
@DeadSith, I'm glad to hear that! Soon I will get the final full version of SQLite word database.

**Comment by ua2004** [comment]
Missing words:
- [x] в'яло
- [x] неї
- [x] дамбах

I think you haven't parsed _"місцевий відмінок"_ in all nouns, e.g., _дамба_ -> _на дамбах_. It consists of two words but only the second one should be parsed (_на/у дамбах_ -> take only _дамбах_).

**Comment by DeadSith** [comment]
I've update the database and added more than 200000 new words, but some words are still missing. For example, "в'яло", I had to add it manually. "місцевий відмінок" was also succesfully parsed, as well as words which have 2 different forms.

**Comment by ua2004** [comment]
200 000? Good job!
