### ISSUE TITLE
Letters disappear when placing them back

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#11]
At the end of the game, when there are no more letters left, a strange bug appears. If you place a non-existing word and then put the letters back they don't jump to their original position. They just disappear instead. Again, this bug was noticed only when there are no more letters in the bag.

**Comment by DeadSith** [comment]
Error is in ChangeBox method. Will be fixed soon.

**Comment by DeadSith** [comment]
Fixed
