### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#14]
Here is the list that are missing in the word database (this list may be further updated):
- [x] теж
- [x] де
- [x] не
- [x] ні

**Comment by DeadSith** [comment]
@ua2004 Updated db, new version is available here
https://onedrive.live.com/redir?resid=C8E263D024CF1123!6236&authkey=!ALwz9VMFC-2Ii9M&ithint=file%2czip

**Comment by ua2004** [comment]
This is great but the words "не" and "ні" somehow are still missing.

**Comment by DeadSith** [comment]
Added these words. I will post link to newest version later in readme file.

**Comment by ua2004** [comment]
New missing words:
- [x] десна
- [x] об
- [x] єноті

**Comment by DeadSith** [comment]
@ua2004 Will be fixed soon. However, post next missing words in issue #10

**Comment by DeadSith** [comment]
And I'm not sure "єноті" is a valid word

**Comment by ua2004** [comment]
@DeadSith, it is a [valid word](http://slovnyk.ua/?swrd=%BA%ED%EE%F2&x=0&y=0) (місцевий відмінок).

**Comment by DeadSith** [comment]
Added words
