### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#15]
```
ArgumentException: The Assembly System.Security is referenced by System.Configuration ('Assets/Plugins/System.Configuration.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:156)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:162)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:162)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:162)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:194)
UnityEditor.HostView:OnGUI()
```

And another one:

```
Error building Player: Extracting referenced dlls failed.
```

**Comment by DeadSith** [comment]
@ua2004
In Build Settings > Player Settings > API Compatibility Level, change to .NET 2.0, not .NET 2.0 subset.

**Comment by DeadSith** [comment]
I will update readme.md tomorrow to refence this issue

**Comment by DeadSith** [comment]
@ua2004 
Latest built version is available [here](https://onedrive.live.com/redir?resid=C8E263D024CF1123!6240&authkey=!AG8x7AoxwjhBzqw&ithint=file%2czip)

**Comment by DeadSith** [comment]
@ua2004 
There was error with tags, I fixed try rebuilding project on your machine. Write me if it works after it, please.

**Comment by ua2004** [comment]
@DeadSith, yes, it finally works. I managed to build it, and it works properly. Thank you.

BTW, I believe the **ProjectSettings** folder should always be added to _git_ in order for the project to work correctly on other machines.

**Comment by DeadSith** [comment]
@ua2004 Thanks for the info. I thought tags were stored in separate file, not in ProjectSettings.

**Comment by ua2004** [comment]
After building the project I get the _.exe_ file, _Data_ folder and some extra 2 files: _player_win_x64.pdb_ and _player_win_x64_s.pdb_. Any idea what are the last two for?

**Comment by DeadSith** [comment]
@ua2004 
They are generated if [debug build](http://stackoverflow.com/questions/29359473/unity-5-pdb-file-on-build-development-build-turned-off) is selected. I think they can be safely deleted

**Comment by ua2004** [comment]
That's weird. _"Development Build"_ is not checked in _"Build Settings"_ window. However, the .pdb files are still generated. But the game works well without them. Thanks for the info though.
