### ISSUE TITLE
Write user IP in text field

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#17]
Previously, when network mode was opened, the user saw his IP address in the text field and could tell it to another player so that they could connect to each other. Now the text field is empty and it is inconvenient for the player to find out his IP.

![image](https://cloud.githubusercontent.com/assets/8424744/15220591/bd252ea6-1870-11e6-9ce0-bd87d4ce9049.png)

**Comment by DeadSith** [comment]
The problem is with sqlite.dll loading.
