### ISSUE TITLE
Asterisk (*) cannot change its value during the game

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#18]
During the game the asterisk (*) replaces some letter. Once the letter is chosen it sould the same remain until the end of the game. It seems that currently asterisk can turn into another letter when building a new word.

![bug](https://cloud.githubusercontent.com/assets/8424744/15238114/5c5f0d68-18dd-11e6-96f4-9f96bf82f5c6.png)

**Comment by DeadSith** [comment]
@ua2004 Started fixing [here](https://github.com/DeadSith/PvP-Scrabble-like-game/tree/asterix-fix). Unfortunately, Android version will not have this fix because of low performance.

**Comment by DeadSith** [comment]
Fixed for HotSeat in 03dfb3adb7dbb6fe0fbf99d55474fc18024ae0b4

**Comment by DeadSith** [comment]
Finished multiplayer. All fixes are merged into master in #22

**Comment by ua2004** [comment]
Awesome! Thank you very much!
