### ISSUE TITLE
Letter from one player "jumps" to another after reverting letters

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#19]
At the end of game 1st player had only an apostrophe, 2nd player had only a letter "л". When 2nd player put his letter in wrong place and pressed button "Повернути всі літери", his letter "л" went back. Also, the apostrophe suddenly disappeared from player 1 and appeared in player 2.

![bug](https://cloud.githubusercontent.com/assets/8424744/16056772/b983c7ac-327f-11e6-87f8-6db52f6ed7f5.png)

**Comment by DeadSith** [comment]
I will start fixing errors next week. Also, I will finally upload new version of database at the beginning of the next week(there were problems with table keys)

**Comment by ua2004** [comment]
Great!

**Comment by DeadSith** [comment]
Was unable to recreate error and found no erros in code
