### ISSUE TITLE
Asterisk (*) letter should have zero score

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#23]
![screen1](https://cloud.githubusercontent.com/assets/8424744/22346234/08850ed6-e40c-11e6-853b-ef1f6ae51f68.png)
After adding an asterisk to the field it becomes a letter with zero score. Which is OK. But after making a perpendicular word the asterisk letter has now a non-zero score.

**Comment by DeadSith** [comment]
Will be fixed in next commit.

**Comment by ua2004** [comment]
It's good but could you make the letter show score 0 on mouse over? Currently it shows 1 or 2 etc. This might confuse the player.
