### ISSUE TITLE
First column and last row don't work

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#24]
![screen2](https://cloud.githubusercontent.com/assets/8424744/22346791/ff31ac8e-e40d-11e6-83b3-dd9f20fc75f6.png)
If a letter is in the first column or in the last row then the whole word is not accepted.

**Comment by DeadSith** [comment]
@ua2004 Just checked. Everything works fine, but it may take a few seconds to process word with *. Was error message displayed, or game was just unresponsible?

**Comment by ua2004** [comment]
Error message displayed that there is no such word. Checked on different words, even without the asterisk. If there is one letter in the first column or last row the word is not accepted by the game.

**Comment by DeadSith** [comment]
Strange, everything works fine for me. [Here](https://1drv.ms/i/s!AiMRzyTQY-LIskVPODZnys--KDwX) is the example.
