### ISSUE TITLE
Too many letters "Ґ" and apostrophes

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#4]
In the original Ukrainian version there is only one letter "Ґ" and one apostrophe. However, at the end of the game they appear three times each.

![bug2](https://cloud.githubusercontent.com/assets/8424744/14826539/ff2ad8c8-0be6-11e6-9c84-fded8b02b63a.png)

**Comment by DeadSith** [comment]
Letters were not removed in SP after changing them
