### ISSUE TITLE
Labels for "singleplayer" and "multiplayer"

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#5]
Please create labels for "singleplayer" and "multiplayer" on github so that the issues will be categorized.

**Comment by DeadSith** [comment]
Created

**Comment by ua2004** [comment]
I suggest to rename these labels. In both cases we have two players so it's a little incorrect to call it Singleplayer mode. What if we call it another way, e.g., Onescreen and Network mode? Or maybe you have any suggestions?

**Comment by ua2004** [comment]
_Hotseat_ and _Network_ modes. Great choice! )
