### ISSUE TITLE
Show score for word

### ISSUE THREAD

**Issue by DeadSith** [DeadSith/PvP-Scrabble-like-game#7]
After the word is successfully checked show player points for this word.

**Comment by ua2004** [comment]
Is it possible to show the score all the time, not only on mouser over?

**Comment by DeadSith** [comment]
@ua2004
For letters: Technically yes, but font size will be too small
For words:  I'm not sure where and how scores will be showed

**Comment by ua2004** [comment]
For words - only when user submits a new word (discussed here #9).

For letters - maybe the points will be shown below the tile on the right side like this:

![image](https://cloud.githubusercontent.com/assets/8424744/14857400/d4bc6084-0ca4-11e6-83a7-ce8c956d30a5.png)

But the different font color maybe.

**Comment by DeadSith** [comment]
Moved to issue #9
